version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn ci
